### ISSUE TITLE
Requirements for building

### ISSUE THREAD

**Issue by hleroy** [papylhomme/diskmonitor#15]
The following packages are required for building on Kubuntu 17.10. It would be worth mentioning it in the requirement section.

extra-cmake-modules
libkf5iconthemes-dev
libkf5notifications-dev
libkf5windowsystem-dev
libkf5xmlgui-dev
qtdeclarative5-dev

**Comment by papylhomme** [comment]
Thanks for the feedback, I've updated the README accordingly, but I'm not quite sure about the dependency on libkf5windowsystem, did you get an error without this package ?

Also, I've added the "generic" name for the dependencies, not the kubuntu package. This is mainly to keep the repo "distribution agnostic" as I won't be able to maintain multiple packaging solution.

And finally if I can abuse your time, did you run into #14 when compiling this project ?

**Comment by hleroy** [comment]
cmake complained about missing file KF5WindowSystemConfig.cmake
I looked it up with "apt-file search KF5WindowSystemConfig.cmake" and found it in 
libkf5windowsystem-dev

Thanks for updating the README. I'll reply about #14 in its own thread.
