### ISSUE TITLE
Applet's size is unbounded and is thus rediculously too large

### ISSUE THREAD

**Issue by Abscissa** [papylhomme/diskmonitor#18]
This project's applet exhibits the same (over-)sizing problem that used to plague many of KDE 5's built-in widgets/applets.

Example/illustration of the exact same problem:
https://forum.kde.org/viewtopic.php?f=289&t=131908

Fix(es) used by KDE 5's built-ins:
https://bugs.kde.org/show_bug.cgi?id=378443

As a side note, I'd like to emphasize that I am absolutely THRILLED to see this program exists. As a former user of Hard Disk Sentinel back in my Windows days, I am *strongly* of the opinion that tools such as this should have long been a *standard* part of *any* operation system installation. And that's particularly because this (like HDSentinel on Windows) provides *proactive* notice of SMART issues, not just a manual poll-based cmdline interface (or worse, NO notice whatsoever, as is the default in most operation systems). Some years back, my old inability to find a program like this on Linux was by far my biggest hesitation at switching my primary desktop from Windows to Linux. So *huge* thanks for making this tool, and also for making it Qt/KDE-based.

**Comment by papylhomme** [comment]
Hello, just to let you know I'm looking into this right now. Thanks for the pointers, you did most of the work.

By the way I'm glad you like it, we happen to share the same view regarding system monitoring ;)

**Comment by papylhomme** [comment]
Seems fixed, can you confirm it ?

**Comment by Abscissa** [comment]
On 4/5/19 12:12 PM, Michaël Lhomme wrote:
> Seems fixed, can you confirm it ?
> 
Thanks, I'll check as soon as I can. It might take a little while though 
since I've never manually built this directly from source (I installed 
it through Arch/Manjaro's AUR), and I don't frequently work with C++ 
codebases much anymore these days. Hopefully it'll go smooth and I won't 
hit trouble with dependencies... (Though I imagine browsing the AUR 
package file should provide any help if I should need it.)

**Comment by Abscissa** [comment]
Ok, I might very well be missing something simple install-related on my 
end, but I'm not seeing it fixed. Here's what I did:

First, I cloned your repo, verified my local was set to master, and used 
the commands in your readme. But when I ran the full DisKMonitor 
application through my "start menu" (or whatever KDE calls it), I just 
ended up with v0.3.1. Adding the widget to my vertical panel resulted in 
the same oversize issue. I'm guessing it just didn't get installed right 
(or installed at all).

Next, I looked up the Arch/Manjaro AUR PKGBUILD for DisKMonitor: 
<https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=diskmonitor>

Taking cues from that, I ran the following from the project's build 
directory:

$ cmake .. \
     -DCMAKE_INSTALL_PREFIX=/usr \
     -DCMAKE_BUILD_TYPE=Release \
     -DLIB_INSTALL_DIR=lib \
     -DKDE_INSTALL_USE_QT_SYS_PATHS=ON
$ make
$ make install

This time, running the full DisKMonitor application through my "start 
menu" yielded an app that reported being "v0.3.3". But adding it to my 
panel once again yielded the same overly-large behavior.

Perhaps I failed to set "DESTDIR=" correctly for make install? Or maybe 
my KDE Plasma session simply needs restarted? (only familiar with KDE as 
a user, not as a dev).

**Comment by papylhomme** [comment]
Can you try to remove the widget and then re-add it ? Also, please check the content of `/usr/share/plasma/plasmoids/org.papylhomme.diskmonitor/contents/ui/main.qml`, you should see `import QtQuick.Layouts 1.11` just below `import QtQuick 2.3`

Finally, you can test the current master more easily using the AUR package `diskmonitor-git`, though you may need to force the installation to overwrite the files installed directly using cmake. I'll release a new version (for the AUR package `diskmonitor`) as soon as this problem is fixed.

**Comment by Abscissa** [comment]
Hmm, that qml file seems to check out fine, the QtQuick.Layouts line is present. Removed/added it, I also tried creating a brand new blank panel and adding the widget to that, but it still exhibited the issue.

Looks like somebody did notice there was a regression in the original Application Launcher issue in Plasma 5.13, perhaps the patch for that issue may help (unless you already incorporated it). Although I'm not sure whether that regression/fix was for the widget itself or something more internal to KDE's general handling of widgets (I'm not really up-to-speed on qml or KDE development): https://bugs.kde.org/show_bug.cgi?id=395594

**Comment by papylhomme** [comment]
Weird, are you running the 5.13 version ? I'm currently running 5.14 on my side. Or maybe I didn't understood what you expected.

Here is a screenshot of a vertical panel with the status icon being centered (instead of growing to the panel width)
![Screenshot_20190407_143404-1](https://user-images.githubusercontent.com/722015/55683685-a86dea00-5942-11e9-864f-93ce3697cf00.png)

**Comment by papylhomme** [comment]
Hello, any news regarding the issue ?

**Comment by Abscissa** [comment]
Sorry, got distracted with other things. Looks like I'm on 5.15. TBH, I'm not clear whether that issue I linked to was something that *only* affected 5.13, or was something that changed in 5.13 thus breaking the original icon-size fix and requiring a new fix.

But your screenshot does indeed look like the expected behavior. Weird that it's not working for me. I'll try rebooting when I get a chance, maybe something's just caching the old version and not refreshing it.

**Comment by Abscissa** [comment]
Looks like it just needed a reboot. It's working fine for me now. Thanks!

**Comment by papylhomme** [comment]
Thanks for the feedback, new version 0.3.3 released in the AUR
