### ISSUE TITLE
Icon of Disk Monitor is incorrect on KDE Plasma Wayland sesison

### ISSUE THREAD

**Issue by glaubersm** [papylhomme/diskmonitor#21]
Hi
I use Disk Monitor 0.3.3 on Arch Linux running the Wayland session of KDE Plasma 5.15.5 desktop environment.
As we can see in the following screenshot, the title bar of Disk Monitor shows
a Wayland generic icon instead of the icon of Disk Monitor.
The task switcher (alt+tab menu) also shows the same Wayland generic icon.
Maybe the following link can help you to solve this issue.
https://community.kde.org/Guidelines_and_HOWTOs/Wayland_Porting_Notes#Application_Icon

![diskmonitor](https://user-images.githubusercontent.com/15967631/57410624-b0c77800-71c1-11e9-9403-b6d432c2d910.png)

**Comment by papylhomme** [comment]
Hi, can you test it using the AUR package diskmonitor-git ? I pushed some updates, seems fixed to me.
And thanks for the link BTW, it helps a lot when the investigation is already done ;)

**Comment by glaubersm** [comment]
Hi
I just tested diskmonitor-git from AUR and can confirm that the bug is fixed.
Thank you.
