### ISSUE TITLE
Dark font in breeze dark theme

### ISSUE THREAD

**Issue by KVAnton-WEB** [papylhomme/diskmonitor#23]
![screenshot](https://i.imgur.com/uF2tf6L.png)
 OS: KDE neon 5.17
 DE: KDE 5.63.0 / Plasma 5.17.1
 WM: KWin
 WM Theme: Breeze Dark
 GTK Theme: Breeze-Dark [GTK2/3]
 Icon Theme: breeze-dark
 Font: Noto Sans Regular

**Comment by glaubersm** [comment]
I have just built master branch on Arch Linux and I can confirm this issue.

Operating System: Arch Linux 
KDE Plasma Version: 5.18.90
KDE Frameworks Version: 5.70.0
Qt Version: 5.15.0 rc2

**Comment by papylhomme** [comment]
Sorry for the delay, should be fixed by 61781723a7c9fc4245f14fa745c1dac5cf5c7c78, can you confirm ?

**Comment by glaubersm** [comment]
Yes, I can confirm. Thank you very much @papylhomme.
