### ISSUE TITLE
Slovenian translation

### ISSUE THREAD

**Issue by matevz** [papylhomme/diskmonitor#24]
I'd like to contribute a Slovenian translation. I requested the new language on Transifex some time ago and it was added. But when I tried "Join team" I got no response. Could you please add me to the translation team? Thanks.

**Comment by papylhomme** [comment]
Sorry, it should be fixed now. Somehow I didn't receive any notification about it, thank you to take the time for this.

**Comment by papylhomme** [comment]
Hi, thanks for your time ! Your translation should be integrated as of a23b39e31b8a4072af8afe6f1887131c9555f6fd

**Comment by papylhomme** [comment]
It don't seems to work on my system, but perhaps I'm missing some configuration regarding locales, can you confirm if it's working on your side ?
